name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9:00 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    name: Update Go Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Update dependencies (all modules)
        run: |
          for module in hyperion adapter/viper; do
            echo "Updating dependencies for $module..."
            (cd $module && go get -u ./... && go mod tidy) || exit 1
          done

      - name: Run tests (all modules)
        run: |
          for module in hyperion adapter/viper; do
            echo "Testing $module..."
            (cd $module && go test ./...) || exit 1
          done

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore(deps): update Go dependencies'
          title: 'chore(deps): Update Go dependencies'
          body: |
            ## Dependency Updates

            This PR updates Go dependencies to their latest versions.

            ### Changes
            - Updated all Go modules to latest versions
            - Ran `go mod tidy`
            - All tests passing

            ### Testing
            ✅ All tests pass with updated dependencies

            **Auto-generated by GitHub Actions**
          branch: deps/auto-update-dependencies
          delete-branch: true
          labels: dependencies,automated

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run Nancy (dependency vulnerability scanner)
        run: |
          go install github.com/sonatype-nexus-community/nancy@latest
          for module in hyperion adapter/viper; do
            echo "Scanning $module with Nancy..."
            (cd $module && go list -json -deps ./... | nancy sleuth) || true
          done

      - name: Run govulncheck (all modules)
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          for module in hyperion adapter/viper; do
            echo "Checking vulnerabilities in $module..."
            (cd $module && govulncheck ./...) || true
          done
